### ISSUE TITLE
Multiple instances of Casper Imaging

### ISSUE THREAD

**Issue by MScottBlake** [macmule/AutoCasperNBI#76]
I am using ACNBI to create USB sticks and Restore partitions for lab machines. After the first use, Casper Imaging launches a second time. This becomes a problem when automatic imaging is checked as one will start to block copy, then the other will start erasing the drive.

I believe it is the OS recreating the previous environment combined with the startup item, but I can't get it to stop manually even.

**Comment by macmule** [comment]
@MScottBlake That's odd.. Can you capture a video of it? I'm not sure how to troubleshoot.

Only guess is it's something like: https://macmule.com/CasperImaging-Chopped.mp4

**Comment by MScottBlake** [comment]
Similar, but imagine both have dots under them because they have both
launched. I'm currently snowed in, but I'll get you a video when I can.

**Comment by dnikles** [comment]
I think what's happening is when running from USB the system is read-write unlike when netbooted. I'm running into the same thing running from USB. If you hcheck "boot to target drive after imaging", casper imaging is still open when the system shuts down, so on next boot it opens again, and also auto launches another instance of casper imaging. I had checked in ACNBI to slim the image down so I don't have the option to change anything in system preferences. What I did was run "defaults write -g ApplePersistence -bool no" in terminal and it fixed this issue. @macmule is there a way to have that as part of the build?

**Comment by macmule** [comment]
@dnikles Nice defaults command. 

Should be easy enough to add.

**Comment by macmule** [comment]
Hmm. I see from googling that's mentioned for 10.7? 

@dnikles guess your seeing it working on 10.11?

**Comment by dnikles** [comment]
I only tested on 10.11. It worked there.

Sent from my iPhone

On Mar 11, 2016, at 3:37 PM, macmule <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm. I see from googling that's mentioned for 10.7?

@dnikles<https://github.com/dnikles> guess your seeing it working on 10.11?

—
Reply to this email directly or view it on GitHub<https://github.com/macmule/AutoCasperNBI/issues/76#issuecomment-195540629>.

________________________________

CONFIDENTIALITY NOTICE: This e-mail, including any attached files, may
contain privileged information, intended for the personal and confidential
use of the recipient(s) named above. If you are not an intended recipient,
please note that you are not permitted to review, print, copy, distribute,
disclose, or otherwise use any information contained in this communication.
If you have received this communication in error, please promptly notify the
sender by e-mail and destroy the original communication, including any
related paper copies.

**Comment by mostlikelee** [comment]
I have it set as a "before" script in the JSS.  Works well.

**Comment by macmule** [comment]
@dnikles, @mostlikelee & @MScottBlake 

I'll add this to 1.3.4, coming soon. But will not be able to test.

1.3.4 should drop early next week at the latest, once done.. please test & report back.

**Comment by macmule** [comment]
@dnikles, @mostlikelee & @MScottBlake

Can you test: https://github.com/macmule/AutoCasperNBI/releases/tag/1.3.4 & advise if this resolves?

**Comment by dnikles** [comment]
Yes it appears to be working correctly for me. Thanks!
Dustin

**Comment by macmule** [comment]
thanks.. in 1.3.4 :)
