### ISSUE TITLE
System Preferences/Launchpad missing from Dock

### ISSUE THREAD

**Issue by jeolsen** [macmule/AutoCasperNBI#98]
Building a NBI with AutoCasperNBI based off of 10.12.X results in a Dock only displaying Finder, Casper Imaging, and Trash.  System Preferences and Launchpad are not displayed.  This was tested on 10.12.1 and 10.12.2 with ACNBI 1.3.4.

**Comment by macmule** [comment]
Actually, this isn't a bug per se.. but the wrong image on my blog!

The Dock should look like:

![screen shot 2017-08-31 at 1 55 38 am](https://user-images.githubusercontent.com/2464974/29915138-c758a324-8e32-11e7-8364-2d549c3eddf6.png)

com.apple.Dock.plist hasn't been modified since release:

![screenshot 2017-08-31 09 54 20](https://user-images.githubusercontent.com/2464974/29915164-d965d488-8e32-11e7-97e7-d3b53656e9a0.png)

**Comment by macmule** [comment]
Updated blog. Thanks!
